### PR TITLE
Delete .vs/InkVerse/FileContentIndex directory

### PR DESCRIPTION
**Pull request by RobotAlbatross**
Not needed lol

### CODE REVIEW

**Comment by atrayav** [comment]
why was this here in the first place

**Comment by RobotAlbatross** [comment]
Dunno lol. That's why I am deleting it

**Review by sweeezin — APPROVED** [review]
approved

**Review by yekalai — COMMENTED** [review]
Pretty based

**Review by yekalai — APPROVED** [review]
???Test

**Pull request closed without merging**
